apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-cron-go
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kube-cron-go
              image: kube-cron-go
              imagePullPolicy: Never # use local docker image
          restartPolicy: OnFailure
